#! /bin/sh
### BEGIN INIT INFO
# Provides:          <wifi_wps_button>
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: allows wif connection using wps button
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

case "$1" in
  start)
    log_begin_msg "Starting wifi connection using WPS button"
    # only run if there's no current wifi connection
    if  ! ifconfig wlan0 | grep -q "inet addr:" ; then
           # grab AP's that support WPS, sort by strength and select the strongest 
            wpa_cli scan_results | grep WPS | sort -r -k3 | awk 'END{print $NF}'  >/tmp/wifi
            read ssid < /tmp/wifi
            wpa_cli wps-pbc $ssid
    fi
    log_end_msg $?
    exit 0
    ;;
  stop)
    # do something to kill the service or cleanup or nothing

    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/home/pi/git/thermostat/thermostat/wifi_wps_button {start|stop}"
    exit 1
    ;;
esac
